/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DataCreatedBody model module.
 * @module model/DataCreatedBody
 * @version 1.0.0
 */
export class DataCreatedBody {
  /**
   * Constructs a new <code>DataCreatedBody</code>.
   * @alias module:model/DataCreatedBody
   * @class
   * @param walletAddress {String} 
   * @param chain {module:model/DataCreatedBody.ChainEnum} 
   */
  constructor(walletAddress, chain) {
    this.walletAddress = walletAddress;
    this.chain = chain;
  }

  /**
   * Constructs a <code>DataCreatedBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DataCreatedBody} obj Optional instance to populate.
   * @return {module:model/DataCreatedBody} The populated <code>DataCreatedBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DataCreatedBody();
      if (data.hasOwnProperty('walletAddress'))
        obj.walletAddress = ApiClient.convertToType(data['walletAddress'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} walletAddress
 */
DataCreatedBody.prototype.walletAddress = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
DataCreatedBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum"
};
/**
 * @member {module:model/DataCreatedBody.ChainEnum} chain
 */
DataCreatedBody.prototype.chain = undefined;

