/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeployDeployCollectionContractBody model module.
 * @module model/DeployDeployCollectionContractBody
 * @version 1.0.0
 */
export class DeployDeployCollectionContractBody {
  /**
   * Constructs a new <code>DeployDeployCollectionContractBody</code>.
   * @alias module:model/DeployDeployCollectionContractBody
   * @class
   * @param contractName {String} 
   * @param contractSymbol {String} 
   * @param recipientAddress {String} 
   * @param chain {module:model/DeployDeployCollectionContractBody.ChainEnum} 
   */
  constructor(contractName, contractSymbol, recipientAddress, chain) {
    this.contractName = contractName;
    this.contractSymbol = contractSymbol;
    this.recipientAddress = recipientAddress;
    this.chain = chain;
  }

  /**
   * Constructs a <code>DeployDeployCollectionContractBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployDeployCollectionContractBody} obj Optional instance to populate.
   * @return {module:model/DeployDeployCollectionContractBody} The populated <code>DeployDeployCollectionContractBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployDeployCollectionContractBody();
      if (data.hasOwnProperty('contractName'))
        obj.contractName = ApiClient.convertToType(data['contractName'], 'String');
      if (data.hasOwnProperty('contractSymbol'))
        obj.contractSymbol = ApiClient.convertToType(data['contractSymbol'], 'String');
      if (data.hasOwnProperty('recipientAddress'))
        obj.recipientAddress = ApiClient.convertToType(data['recipientAddress'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
      if (data.hasOwnProperty('contractType'))
        obj.contractType = ApiClient.convertToType(data['contractType'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contractName
 */
DeployDeployCollectionContractBody.prototype.contractName = undefined;

/**
 * @member {String} contractSymbol
 */
DeployDeployCollectionContractBody.prototype.contractSymbol = undefined;

/**
 * @member {String} recipientAddress
 */
DeployDeployCollectionContractBody.prototype.recipientAddress = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
DeployDeployCollectionContractBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "goerli"
   * @const
   */
  goerli: "goerli",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "bsc"
   * @const
   */
  bsc: "bsc",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/DeployDeployCollectionContractBody.ChainEnum} chain
 */
DeployDeployCollectionContractBody.prototype.chain = undefined;

/**
 * Allowed values for the <code>contractType</code> property.
 * @enum {String}
 * @readonly
 */
DeployDeployCollectionContractBody.ContractTypeEnum = {
  /**
   * value: "nft721"
   * @const
   */
  nft721: "nft721",

  /**
   * value: "nft721A"
   * @const
   */
  nft721A: "nft721A"
};
/**
 * @member {module:model/DeployDeployCollectionContractBody.ContractTypeEnum} contractType
 */
DeployDeployCollectionContractBody.prototype.contractType = undefined;

