/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeployBurnBody model module.
 * @module model/DeployBurnBody
 * @version 1.0.0
 */
export class DeployBurnBody {
  /**
   * Constructs a new <code>DeployBurnBody</code>.
   * @alias module:model/DeployBurnBody
   * @class
   * @param contractAddress {String} 
   * @param tokenId {String} 
   * @param chain {module:model/DeployBurnBody.ChainEnum} 
   */
  constructor(contractAddress, tokenId, chain) {
    this.contractAddress = contractAddress;
    this.tokenId = tokenId;
    this.chain = chain;
  }

  /**
   * Constructs a <code>DeployBurnBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployBurnBody} obj Optional instance to populate.
   * @return {module:model/DeployBurnBody} The populated <code>DeployBurnBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployBurnBody();
      if (data.hasOwnProperty('contractAddress'))
        obj.contractAddress = ApiClient.convertToType(data['contractAddress'], 'String');
      if (data.hasOwnProperty('tokenId'))
        obj.tokenId = ApiClient.convertToType(data['tokenId'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contractAddress
 */
DeployBurnBody.prototype.contractAddress = undefined;

/**
 * @member {String} tokenId
 */
DeployBurnBody.prototype.tokenId = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
DeployBurnBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "goerli"
   * @const
   */
  goerli: "goerli",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "bsc"
   * @const
   */
  bsc: "bsc",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/DeployBurnBody.ChainEnum} chain
 */
DeployBurnBody.prototype.chain = undefined;

