/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeployUpdateContractBody model module.
 * @module model/DeployUpdateContractBody
 * @version 1.0.0
 */
export class DeployUpdateContractBody {
  /**
   * Constructs a new <code>DeployUpdateContractBody</code>.
   * @alias module:model/DeployUpdateContractBody
   * @class
   * @param contractAddress {String} 
   * @param chain {module:model/DeployUpdateContractBody.ChainEnum} 
   */
  constructor(contractAddress, chain) {
    this.contractAddress = contractAddress;
    this.chain = chain;
  }

  /**
   * Constructs a <code>DeployUpdateContractBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeployUpdateContractBody} obj Optional instance to populate.
   * @return {module:model/DeployUpdateContractBody} The populated <code>DeployUpdateContractBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeployUpdateContractBody();
      if (data.hasOwnProperty('contractAddress'))
        obj.contractAddress = ApiClient.convertToType(data['contractAddress'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
      if (data.hasOwnProperty('tokenURIPrereveal'))
        obj.tokenURIPrereveal = ApiClient.convertToType(data['tokenURIPrereveal'], 'String');
      if (data.hasOwnProperty('allowListMintStartTime'))
        obj.allowListMintStartTime = ApiClient.convertToType(data['allowListMintStartTime'], 'String');
      if (data.hasOwnProperty('publicSaleStartTime'))
        obj.publicSaleStartTime = ApiClient.convertToType(data['publicSaleStartTime'], 'String');
      if (data.hasOwnProperty('allowlistMintPriceInWei'))
        obj.allowlistMintPriceInWei = ApiClient.convertToType(data['allowlistMintPriceInWei'], 'String');
      if (data.hasOwnProperty('publicPriceInWei'))
        obj.publicPriceInWei = ApiClient.convertToType(data['publicPriceInWei'], 'String');
      if (data.hasOwnProperty('metadataFrozen'))
        obj.metadataFrozen = ApiClient.convertToType(data['metadataFrozen'], 'String');
      if (data.hasOwnProperty('baseTokenURI'))
        obj.baseTokenURI = ApiClient.convertToType(data['baseTokenURI'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contractAddress
 */
DeployUpdateContractBody.prototype.contractAddress = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
DeployUpdateContractBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "goerli"
   * @const
   */
  goerli: "goerli",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "bsc"
   * @const
   */
  bsc: "bsc",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/DeployUpdateContractBody.ChainEnum} chain
 */
DeployUpdateContractBody.prototype.chain = undefined;

/**
 * @member {String} tokenURIPrereveal
 */
DeployUpdateContractBody.prototype.tokenURIPrereveal = undefined;

/**
 * @member {String} allowListMintStartTime
 */
DeployUpdateContractBody.prototype.allowListMintStartTime = undefined;

/**
 * @member {String} publicSaleStartTime
 */
DeployUpdateContractBody.prototype.publicSaleStartTime = undefined;

/**
 * @member {String} allowlistMintPriceInWei
 */
DeployUpdateContractBody.prototype.allowlistMintPriceInWei = undefined;

/**
 * @member {String} publicPriceInWei
 */
DeployUpdateContractBody.prototype.publicPriceInWei = undefined;

/**
 * @member {String} metadataFrozen
 */
DeployUpdateContractBody.prototype.metadataFrozen = undefined;

/**
 * @member {String} baseTokenURI
 */
DeployUpdateContractBody.prototype.baseTokenURI = undefined;

