/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MintCustomContractMintFromFileBody model module.
 * @module model/MintCustomContractMintFromFileBody
 * @version 1.0.0
 */
export class MintCustomContractMintFromFileBody {
  /**
   * Constructs a new <code>MintCustomContractMintFromFileBody</code>.
   * @alias module:model/MintCustomContractMintFromFileBody
   * @class
   * @param filePath {Blob} 
   * @param name {String} 
   * @param description {String} 
   * @param recipientAddress {String} 
   * @param contractAddress {String} 
   * @param chain {module:model/MintCustomContractMintFromFileBody.ChainEnum} 
   */
  constructor(filePath, name, description, recipientAddress, contractAddress, chain) {
    this.filePath = filePath;
    this.name = name;
    this.description = description;
    this.recipientAddress = recipientAddress;
    this.contractAddress = contractAddress;
    this.chain = chain;
  }

  /**
   * Constructs a <code>MintCustomContractMintFromFileBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MintCustomContractMintFromFileBody} obj Optional instance to populate.
   * @return {module:model/MintCustomContractMintFromFileBody} The populated <code>MintCustomContractMintFromFileBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MintCustomContractMintFromFileBody();
      if (data.hasOwnProperty('filePath'))
        obj.filePath = ApiClient.convertToType(data['filePath'], 'Blob');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('recipientAddress'))
        obj.recipientAddress = ApiClient.convertToType(data['recipientAddress'], 'String');
      if (data.hasOwnProperty('contractAddress'))
        obj.contractAddress = ApiClient.convertToType(data['contractAddress'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Blob} filePath
 */
MintCustomContractMintFromFileBody.prototype.filePath = undefined;

/**
 * @member {String} name
 */
MintCustomContractMintFromFileBody.prototype.name = undefined;

/**
 * @member {String} description
 */
MintCustomContractMintFromFileBody.prototype.description = undefined;

/**
 * @member {String} recipientAddress
 */
MintCustomContractMintFromFileBody.prototype.recipientAddress = undefined;

/**
 * @member {String} contractAddress
 */
MintCustomContractMintFromFileBody.prototype.contractAddress = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
MintCustomContractMintFromFileBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/MintCustomContractMintFromFileBody.ChainEnum} chain
 */
MintCustomContractMintFromFileBody.prototype.chain = undefined;

