/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NFTData model module.
 * @module model/NFTData
 * @version 1.0.0
 */
export class NFTData {
  /**
   * Constructs a new <code>NFTData</code>.
   * @alias module:model/NFTData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NFTData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NFTData} obj Optional instance to populate.
   * @return {module:model/NFTData} The populated <code>NFTData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NFTData();
      if (data.hasOwnProperty('contractAddress'))
        obj.contractAddress = ApiClient.convertToType(data['contractAddress'], 'String');
      if (data.hasOwnProperty('tokenID'))
        obj.tokenID = ApiClient.convertToType(data['tokenID'], 'String');
      if (data.hasOwnProperty('tokenName'))
        obj.tokenName = ApiClient.convertToType(data['tokenName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contractAddress
 */
NFTData.prototype.contractAddress = undefined;

/**
 * @member {String} tokenID
 */
NFTData.prototype.tokenID = undefined;

/**
 * @member {String} tokenName
 */
NFTData.prototype.tokenName = undefined;

