/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SendQuickSendBody model module.
 * @module model/SendQuickSendBody
 * @version 1.0.0
 */
export class SendQuickSendBody {
  /**
   * Constructs a new <code>SendQuickSendBody</code>.
   * @alias module:model/SendQuickSendBody
   * @class
   * @param sourceChain {module:model/SendQuickSendBody.SourceChainEnum} 
   * @param destChain {module:model/SendQuickSendBody.DestChainEnum} 
   * @param tokenId {String} 
   * @param sourceAddress {String} 
   * @param recipientAddress {String} 
   */
  constructor(sourceChain, destChain, tokenId, sourceAddress, recipientAddress) {
    this.sourceChain = sourceChain;
    this.destChain = destChain;
    this.tokenId = tokenId;
    this.sourceAddress = sourceAddress;
    this.recipientAddress = recipientAddress;
  }

  /**
   * Constructs a <code>SendQuickSendBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendQuickSendBody} obj Optional instance to populate.
   * @return {module:model/SendQuickSendBody} The populated <code>SendQuickSendBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendQuickSendBody();
      if (data.hasOwnProperty('sourceChain'))
        obj.sourceChain = ApiClient.convertToType(data['sourceChain'], 'String');
      if (data.hasOwnProperty('destChain'))
        obj.destChain = ApiClient.convertToType(data['destChain'], 'String');
      if (data.hasOwnProperty('tokenId'))
        obj.tokenId = ApiClient.convertToType(data['tokenId'], 'String');
      if (data.hasOwnProperty('sourceAddress'))
        obj.sourceAddress = ApiClient.convertToType(data['sourceAddress'], 'String');
      if (data.hasOwnProperty('recipientAddress'))
        obj.recipientAddress = ApiClient.convertToType(data['recipientAddress'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>sourceChain</code> property.
 * @enum {String}
 * @readonly
 */
SendQuickSendBody.SourceChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/SendQuickSendBody.SourceChainEnum} sourceChain
 */
SendQuickSendBody.prototype.sourceChain = undefined;

/**
 * Allowed values for the <code>destChain</code> property.
 * @enum {String}
 * @readonly
 */
SendQuickSendBody.DestChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "mumbai"
   * @const
   */
  mumbai: "mumbai",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/SendQuickSendBody.DestChainEnum} destChain
 */
SendQuickSendBody.prototype.destChain = undefined;

/**
 * @member {String} tokenId
 */
SendQuickSendBody.prototype.tokenId = undefined;

/**
 * @member {String} sourceAddress
 */
SendQuickSendBody.prototype.sourceAddress = undefined;

/**
 * @member {String} recipientAddress
 */
SendQuickSendBody.prototype.recipientAddress = undefined;

