/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StoreMetadataFromImageBody model module.
 * @module model/StoreMetadataFromImageBody
 * @version 1.0.0
 */
export class StoreMetadataFromImageBody {
  /**
   * Constructs a new <code>StoreMetadataFromImageBody</code>.
   * @alias module:model/StoreMetadataFromImageBody
   * @class
   * @param filePath {Blob} 
   * @param name {String} 
   * @param description {String} 
   */
  constructor(filePath, name, description) {
    this.filePath = filePath;
    this.name = name;
    this.description = description;
  }

  /**
   * Constructs a <code>StoreMetadataFromImageBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoreMetadataFromImageBody} obj Optional instance to populate.
   * @return {module:model/StoreMetadataFromImageBody} The populated <code>StoreMetadataFromImageBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StoreMetadataFromImageBody();
      if (data.hasOwnProperty('filePath'))
        obj.filePath = ApiClient.convertToType(data['filePath'], 'Blob');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Blob} filePath
 */
StoreMetadataFromImageBody.prototype.filePath = undefined;

/**
 * @member {String} name
 */
StoreMetadataFromImageBody.prototype.name = undefined;

/**
 * @member {String} description
 */
StoreMetadataFromImageBody.prototype.description = undefined;

