/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StoreUploadDirectoryBody model module.
 * @module model/StoreUploadDirectoryBody
 * @version 1.0.0
 */
export class StoreUploadDirectoryBody {
  /**
   * Constructs a new <code>StoreUploadDirectoryBody</code>.
   * @alias module:model/StoreUploadDirectoryBody
   * @class
   * @param filePath {Blob} 
   */
  constructor(filePath) {
    this.filePath = filePath;
  }

  /**
   * Constructs a <code>StoreUploadDirectoryBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoreUploadDirectoryBody} obj Optional instance to populate.
   * @return {module:model/StoreUploadDirectoryBody} The populated <code>StoreUploadDirectoryBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StoreUploadDirectoryBody();
      if (data.hasOwnProperty('filePath'))
        obj.filePath = ApiClient.convertToType(data['filePath'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} filePath
 */
StoreUploadDirectoryBody.prototype.filePath = undefined;

