/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UpdateTransferOperatorBody model module.
 * @module model/UpdateTransferOperatorBody
 * @version 1.0.0
 */
export class UpdateTransferOperatorBody {
  /**
   * Constructs a new <code>UpdateTransferOperatorBody</code>.
   * @alias module:model/UpdateTransferOperatorBody
   * @class
   * @param contractAddress {String} 
   * @param newOperatorAddress {String} 
   * @param chain {module:model/UpdateTransferOperatorBody.ChainEnum} 
   */
  constructor(contractAddress, newOperatorAddress, chain) {
    this.contractAddress = contractAddress;
    this.newOperatorAddress = newOperatorAddress;
    this.chain = chain;
  }

  /**
   * Constructs a <code>UpdateTransferOperatorBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateTransferOperatorBody} obj Optional instance to populate.
   * @return {module:model/UpdateTransferOperatorBody} The populated <code>UpdateTransferOperatorBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UpdateTransferOperatorBody();
      if (data.hasOwnProperty('contractAddress'))
        obj.contractAddress = ApiClient.convertToType(data['contractAddress'], 'String');
      if (data.hasOwnProperty('newOperatorAddress'))
        obj.newOperatorAddress = ApiClient.convertToType(data['newOperatorAddress'], 'String');
      if (data.hasOwnProperty('chain'))
        obj.chain = ApiClient.convertToType(data['chain'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} contractAddress
 */
UpdateTransferOperatorBody.prototype.contractAddress = undefined;

/**
 * @member {String} newOperatorAddress
 */
UpdateTransferOperatorBody.prototype.newOperatorAddress = undefined;

/**
 * Allowed values for the <code>chain</code> property.
 * @enum {String}
 * @readonly
 */
UpdateTransferOperatorBody.ChainEnum = {
  /**
   * value: "rinkeby"
   * @const
   */
  rinkeby: "rinkeby",

  /**
   * value: "goerli"
   * @const
   */
  goerli: "goerli",

  /**
   * value: "bsc-testnet"
   * @const
   */
  bscTestnet: "bsc-testnet",

  /**
   * value: "fuji"
   * @const
   */
  fuji: "fuji",

  /**
   * value: "arbitrum-rinkeby"
   * @const
   */
  arbitrumRinkeby: "arbitrum-rinkeby",

  /**
   * value: "fantom-testnet"
   * @const
   */
  fantomTestnet: "fantom-testnet",

  /**
   * value: "ethereum"
   * @const
   */
  ethereum: "ethereum",

  /**
   * value: "bsc"
   * @const
   */
  bsc: "bsc",

  /**
   * value: "avalanche"
   * @const
   */
  avalanche: "avalanche",

  /**
   * value: "polygon"
   * @const
   */
  polygon: "polygon",

  /**
   * value: "arbitrum"
   * @const
   */
  arbitrum: "arbitrum",

  /**
   * value: "optimism"
   * @const
   */
  optimism: "optimism",

  /**
   * value: "fantom"
   * @const
   */
  fantom: "fantom"
};
/**
 * @member {module:model/UpdateTransferOperatorBody.ChainEnum} chain
 */
UpdateTransferOperatorBody.prototype.chain = undefined;

