/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserOpsTransactionDetailsBody model module.
 * @module model/UserOpsTransactionDetailsBody
 * @version 1.0.0
 */
export class UserOpsTransactionDetailsBody {
  /**
   * Constructs a new <code>UserOpsTransactionDetailsBody</code>.
   * @alias module:model/UserOpsTransactionDetailsBody
   * @class
   * @param transactionId {String} 
   */
  constructor(transactionId) {
    this.transactionId = transactionId;
  }

  /**
   * Constructs a <code>UserOpsTransactionDetailsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserOpsTransactionDetailsBody} obj Optional instance to populate.
   * @return {module:model/UserOpsTransactionDetailsBody} The populated <code>UserOpsTransactionDetailsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserOpsTransactionDetailsBody();
      if (data.hasOwnProperty('transactionId'))
        obj.transactionId = ApiClient.convertToType(data['transactionId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} transactionId
 */
UserOpsTransactionDetailsBody.prototype.transactionId = undefined;

