/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Error} from '../model/Error';
import {InlineResponse2001} from '../model/InlineResponse2001';

/**
* User service.
* @module api/UserApi
* @version 1.0.0
*/
export class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the nftUserOpsAllowListSharesForAddressPost operation.
     * @callback moduleapi/UserApi~nftUserOpsAllowListSharesForAddressPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Allowlist Shares
     * Display Allowlist shares for a specific address.
     * @param {String} contractAddress 
     * @param {String} allowListAddress 
     * @param {module:model/String} chain 
     * @param {module:api/UserApi~nftUserOpsAllowListSharesForAddressPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsAllowListSharesForAddressPost(contractAddress, allowListAddress, chain, callback) {
      
      let postBody = null;
      // verify the required parameter 'contractAddress' is set
      if (contractAddress === undefined || contractAddress === null) {
        throw new Error("Missing the required parameter 'contractAddress' when calling nftUserOpsAllowListSharesForAddressPost");
      }
      // verify the required parameter 'allowListAddress' is set
      if (allowListAddress === undefined || allowListAddress === null) {
        throw new Error("Missing the required parameter 'allowListAddress' when calling nftUserOpsAllowListSharesForAddressPost");
      }
      // verify the required parameter 'chain' is set
      if (chain === undefined || chain === null) {
        throw new Error("Missing the required parameter 'chain' when calling nftUserOpsAllowListSharesForAddressPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'contractAddress': contractAddress,'allowListAddress': allowListAddress,'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/allowListSharesForAddress', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsContractPaymentDetailsPost operation.
     * @callback moduleapi/UserApi~nftUserOpsContractPaymentDetailsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Payee Payment Details
     * Display payment details for a specific payee of a contract.
     * @param {String} contractAddress 
     * @param {String} payeeAddress 
     * @param {module:model/String} chain 
     * @param {module:api/UserApi~nftUserOpsContractPaymentDetailsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsContractPaymentDetailsPost(contractAddress, payeeAddress, chain, callback) {
      
      let postBody = null;
      // verify the required parameter 'contractAddress' is set
      if (contractAddress === undefined || contractAddress === null) {
        throw new Error("Missing the required parameter 'contractAddress' when calling nftUserOpsContractPaymentDetailsPost");
      }
      // verify the required parameter 'payeeAddress' is set
      if (payeeAddress === undefined || payeeAddress === null) {
        throw new Error("Missing the required parameter 'payeeAddress' when calling nftUserOpsContractPaymentDetailsPost");
      }
      // verify the required parameter 'chain' is set
      if (chain === undefined || chain === null) {
        throw new Error("Missing the required parameter 'chain' when calling nftUserOpsContractPaymentDetailsPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'contractAddress': contractAddress,'payeeAddress': payeeAddress,'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/contractPaymentDetails', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsDeployedContractsGet operation.
     * @callback moduleapi/UserApi~nftUserOpsDeployedContractsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve deployed contracts
     * Produce a list of all your deployed contracts
     * @param {module:api/UserApi~nftUserOpsDeployedContractsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsDeployedContractsGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/deployedContracts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsIpfsUploadsGet operation.
     * @callback moduleapi/UserApi~nftUserOpsIpfsUploadsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve your uploaded IPFS files
     * Produce a list of all your minted NFTs
     * @param {module:api/UserApi~nftUserOpsIpfsUploadsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsIpfsUploadsGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/ipfsUploads', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsNftsMintedGet operation.
     * @callback moduleapi/UserApi~nftUserOpsNftsMintedGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve your minted NFTs
     * Produce a list of all your minted NFTs
     * @param {module:api/UserApi~nftUserOpsNftsMintedGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsNftsMintedGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/nftsMinted', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsPayeeAtIndexPost operation.
     * @callback moduleapi/UserApi~nftUserOpsPayeeAtIndexPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Payee
     * Display details of Payee at a certain Index.
     * @param {String} contractAddress 
     * @param {String} index 
     * @param {module:model/String} chain 
     * @param {module:api/UserApi~nftUserOpsPayeeAtIndexPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsPayeeAtIndexPost(contractAddress, index, chain, callback) {
      
      let postBody = null;
      // verify the required parameter 'contractAddress' is set
      if (contractAddress === undefined || contractAddress === null) {
        throw new Error("Missing the required parameter 'contractAddress' when calling nftUserOpsPayeeAtIndexPost");
      }
      // verify the required parameter 'index' is set
      if (index === undefined || index === null) {
        throw new Error("Missing the required parameter 'index' when calling nftUserOpsPayeeAtIndexPost");
      }
      // verify the required parameter 'chain' is set
      if (chain === undefined || chain === null) {
        throw new Error("Missing the required parameter 'chain' when calling nftUserOpsPayeeAtIndexPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'contractAddress': contractAddress,'index': index,'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/payeeAtIndex', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsTransactionDetailsPost operation.
     * @callback moduleapi/UserApi~nftUserOpsTransactionDetailsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve specific transaction details
     * Get details for a specific transaction
     * @param {String} transactionId 
     * @param {module:api/UserApi~nftUserOpsTransactionDetailsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsTransactionDetailsPost(transactionId, callback) {
      
      let postBody = null;
      // verify the required parameter 'transactionId' is set
      if (transactionId === undefined || transactionId === null) {
        throw new Error("Missing the required parameter 'transactionId' when calling nftUserOpsTransactionDetailsPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'transactionId': transactionId
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/transactionDetails', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the nftUserOpsUserCollectionContractDetailsPost operation.
     * @callback moduleapi/UserApi~nftUserOpsUserCollectionContractDetailsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Contract Details
     * Display details of your collection contract.
     * @param {String} contractAddress 
     * @param {module:model/String} chain 
     * @param {module:api/UserApi~nftUserOpsUserCollectionContractDetailsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    nftUserOpsUserCollectionContractDetailsPost(contractAddress, chain, callback) {
      
      let postBody = null;
      // verify the required parameter 'contractAddress' is set
      if (contractAddress === undefined || contractAddress === null) {
        throw new Error("Missing the required parameter 'contractAddress' when calling nftUserOpsUserCollectionContractDetailsPost");
      }
      // verify the required parameter 'chain' is set
      if (chain === undefined || chain === null) {
        throw new Error("Missing the required parameter 'chain' when calling nftUserOpsUserCollectionContractDetailsPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        'contractAddress': contractAddress,'chain': chain
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/nft/userOps/userCollectionContractDetails', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}