/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AuthTokens', function() {
      beforeEach(function() {
        instance = new VerbwireApiDocumentation.AuthTokens();
      });

      it('should create an instance of AuthTokens', function() {
        // TODO: update the code to test AuthTokens
        expect(instance).to.be.a(VerbwireApiDocumentation.AuthTokens);
      });

      it('should have the property access (base name: "access")', function() {
        // TODO: update the code to test the property access
        expect(instance).to.have.property('access');
        // expect(instance.access).to.be(expectedValueLiteral);
      });

      it('should have the property refresh (base name: "refresh")', function() {
        // TODO: update the code to test the property refresh
        expect(instance).to.have.property('refresh');
        // expect(instance.refresh).to.be(expectedValueLiteral);
      });

    });
  });

}));
