/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DeployUpdateContractBody', function() {
      beforeEach(function() {
        instance = new VerbwireApiDocumentation.DeployUpdateContractBody();
      });

      it('should create an instance of DeployUpdateContractBody', function() {
        // TODO: update the code to test DeployUpdateContractBody
        expect(instance).to.be.a(VerbwireApiDocumentation.DeployUpdateContractBody);
      });

      it('should have the property contractAddress (base name: "contractAddress")', function() {
        // TODO: update the code to test the property contractAddress
        expect(instance).to.have.property('contractAddress');
        // expect(instance.contractAddress).to.be(expectedValueLiteral);
      });

      it('should have the property chain (base name: "chain")', function() {
        // TODO: update the code to test the property chain
        expect(instance).to.have.property('chain');
        // expect(instance.chain).to.be(expectedValueLiteral);
      });

      it('should have the property tokenURIPrereveal (base name: "tokenURIPrereveal")', function() {
        // TODO: update the code to test the property tokenURIPrereveal
        expect(instance).to.have.property('tokenURIPrereveal');
        // expect(instance.tokenURIPrereveal).to.be(expectedValueLiteral);
      });

      it('should have the property allowListMintStartTime (base name: "allowListMintStartTime")', function() {
        // TODO: update the code to test the property allowListMintStartTime
        expect(instance).to.have.property('allowListMintStartTime');
        // expect(instance.allowListMintStartTime).to.be(expectedValueLiteral);
      });

      it('should have the property publicSaleStartTime (base name: "publicSaleStartTime")', function() {
        // TODO: update the code to test the property publicSaleStartTime
        expect(instance).to.have.property('publicSaleStartTime');
        // expect(instance.publicSaleStartTime).to.be(expectedValueLiteral);
      });

      it('should have the property allowlistMintPriceInWei (base name: "allowlistMintPriceInWei")', function() {
        // TODO: update the code to test the property allowlistMintPriceInWei
        expect(instance).to.have.property('allowlistMintPriceInWei');
        // expect(instance.allowlistMintPriceInWei).to.be(expectedValueLiteral);
      });

      it('should have the property publicPriceInWei (base name: "publicPriceInWei")', function() {
        // TODO: update the code to test the property publicPriceInWei
        expect(instance).to.have.property('publicPriceInWei');
        // expect(instance.publicPriceInWei).to.be(expectedValueLiteral);
      });

      it('should have the property metadataFrozen (base name: "metadataFrozen")', function() {
        // TODO: update the code to test the property metadataFrozen
        expect(instance).to.have.property('metadataFrozen');
        // expect(instance.metadataFrozen).to.be(expectedValueLiteral);
      });

      it('should have the property baseTokenURI (base name: "baseTokenURI")', function() {
        // TODO: update the code to test the property baseTokenURI
        expect(instance).to.have.property('baseTokenURI');
        // expect(instance.baseTokenURI).to.be(expectedValueLiteral);
      });

    });
  });

}));
