/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SendQuickSendBody', function() {
      beforeEach(function() {
        instance = new VerbwireApiDocumentation.SendQuickSendBody();
      });

      it('should create an instance of SendQuickSendBody', function() {
        // TODO: update the code to test SendQuickSendBody
        expect(instance).to.be.a(VerbwireApiDocumentation.SendQuickSendBody);
      });

      it('should have the property sourceChain (base name: "sourceChain")', function() {
        // TODO: update the code to test the property sourceChain
        expect(instance).to.have.property('sourceChain');
        // expect(instance.sourceChain).to.be(expectedValueLiteral);
      });

      it('should have the property destChain (base name: "destChain")', function() {
        // TODO: update the code to test the property destChain
        expect(instance).to.have.property('destChain');
        // expect(instance.destChain).to.be(expectedValueLiteral);
      });

      it('should have the property tokenId (base name: "tokenId")', function() {
        // TODO: update the code to test the property tokenId
        expect(instance).to.have.property('tokenId');
        // expect(instance.tokenId).to.be(expectedValueLiteral);
      });

      it('should have the property sourceAddress (base name: "sourceAddress")', function() {
        // TODO: update the code to test the property sourceAddress
        expect(instance).to.have.property('sourceAddress');
        // expect(instance.sourceAddress).to.be(expectedValueLiteral);
      });

      it('should have the property recipientAddress (base name: "recipientAddress")', function() {
        // TODO: update the code to test the property recipientAddress
        expect(instance).to.have.property('recipientAddress');
        // expect(instance.recipientAddress).to.be(expectedValueLiteral);
      });

    });
  });

}));
