/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.DeployApi();
  });

  describe('(package)', function() {
    describe('DeployApi', function() {
      describe('nftDeployDeployCollectionContractPost', function() {
        it('should call nftDeployDeployCollectionContractPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftDeployDeployCollectionContractPost call and complete the assertions
          /*

          instance.nftDeployDeployCollectionContractPost(contractName, contractSymbol, recipientAddress, chain, contractType, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftDeployDeployCustomContractPost', function() {
        it('should call nftDeployDeployCustomContractPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftDeployDeployCustomContractPost call and complete the assertions
          /*

          instance.nftDeployDeployCustomContractPost(contractName, contractSymbol, recipientAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2011);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUpdateInitCollectionContractPost', function() {
        it('should call nftUpdateInitCollectionContractPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUpdateInitCollectionContractPost call and complete the assertions
          /*

          instance.nftUpdateInitCollectionContractPost(contractAddress, maxMintPerAddress, totalReserveQty, totalAllowlistQty, maxSupply, maxMintableBatchSize, royaltiesInBps, royaltiesAddress, ownerAddress, tokenURIPrereveal, baseTokenURI, allowListMintStartTime, publicSaleStartTime, allowlistMintPriceInWei, publicPriceInWei, metadataFrozen, recipientAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2013);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
