/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.StoreApi();
  });

  describe('(package)', function() {
    describe('StoreApi', function() {
      describe('nftStoreFileFromUrlPost', function() {
        it('should call nftStoreFileFromUrlPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftStoreFileFromUrlPost call and complete the assertions
          /*

          instance.nftStoreFileFromUrlPost(fileUrl, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse20111);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftStoreFilePost', function() {
        it('should call nftStoreFilePost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftStoreFilePost call and complete the assertions
          /*

          instance.nftStoreFilePost(filePath, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse20110);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftStoreMetadataFromImagePost', function() {
        it('should call nftStoreMetadataFromImagePost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftStoreMetadataFromImagePost call and complete the assertions
          /*

          instance.nftStoreMetadataFromImagePost(filePath, name, description, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse20113);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftStoreMetadataFromImageUrlPost', function() {
        it('should call nftStoreMetadataFromImageUrlPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftStoreMetadataFromImageUrlPost call and complete the assertions
          /*

          instance.nftStoreMetadataFromImageUrlPost(fileUrl, name, description, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse20112);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftStoreUploadDirectoryPost', function() {
        it('should call nftStoreUploadDirectoryPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftStoreUploadDirectoryPost call and complete the assertions
          /*

          instance.nftStoreUploadDirectoryPost(filePath, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse20114);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
