/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.UpdateApi();
  });

  describe('(package)', function() {
    describe('UpdateApi', function() {
      describe('nftDeployUpdateContractPost', function() {
        it('should call nftDeployUpdateContractPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftDeployUpdateContractPost call and complete the assertions
          /*

          instance.nftDeployUpdateContractPost(contractAddress, chain, tokenURIPrereveal, allowListMintStartTime, publicSaleStartTime, allowlistMintPriceInWei, publicPriceInWei, metadataFrozen, baseTokenURI, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftDeployUpdateWithdrawFundsPost', function() {
        it('should call nftDeployUpdateWithdrawFundsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftDeployUpdateWithdrawFundsPost call and complete the assertions
          /*

          instance.nftDeployUpdateWithdrawFundsPost(contractAddress, withdrawAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUpdateAddToAllowListPost', function() {
        it('should call nftUpdateAddToAllowListPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUpdateAddToAllowListPost call and complete the assertions
          /*

          instance.nftUpdateAddToAllowListPost(contractAddress, addresses, mintSlots, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUpdateTransferOperatorPost', function() {
        it('should call nftUpdateTransferOperatorPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUpdateTransferOperatorPost call and complete the assertions
          /*

          instance.nftUpdateTransferOperatorPost(contractAddress, newOperatorAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
