/*
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VerbwireApiDocumentation);
  }
}(this, function(expect, VerbwireApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VerbwireApiDocumentation.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('nftUserOpsAllowListSharesForAddressPost', function() {
        it('should call nftUserOpsAllowListSharesForAddressPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUserOpsAllowListSharesForAddressPost call and complete the assertions
          /*

          instance.nftUserOpsAllowListSharesForAddressPost(contractAddress, allowListAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsContractPaymentDetailsPost', function() {
        it('should call nftUserOpsContractPaymentDetailsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUserOpsContractPaymentDetailsPost call and complete the assertions
          /*

          instance.nftUserOpsContractPaymentDetailsPost(contractAddress, payeeAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsDeployedContractsGet', function() {
        it('should call nftUserOpsDeployedContractsGet successfully', function(done) {
          // TODO: uncomment nftUserOpsDeployedContractsGet call and complete the assertions
          /*

          instance.nftUserOpsDeployedContractsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsIpfsUploadsGet', function() {
        it('should call nftUserOpsIpfsUploadsGet successfully', function(done) {
          // TODO: uncomment nftUserOpsIpfsUploadsGet call and complete the assertions
          /*

          instance.nftUserOpsIpfsUploadsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsNftsMintedGet', function() {
        it('should call nftUserOpsNftsMintedGet successfully', function(done) {
          // TODO: uncomment nftUserOpsNftsMintedGet call and complete the assertions
          /*

          instance.nftUserOpsNftsMintedGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsPayeeAtIndexPost', function() {
        it('should call nftUserOpsPayeeAtIndexPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUserOpsPayeeAtIndexPost call and complete the assertions
          /*

          instance.nftUserOpsPayeeAtIndexPost(contractAddress, index, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsTransactionDetailsPost', function() {
        it('should call nftUserOpsTransactionDetailsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUserOpsTransactionDetailsPost call and complete the assertions
          /*

          instance.nftUserOpsTransactionDetailsPost(transactionId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('nftUserOpsUserCollectionContractDetailsPost', function() {
        it('should call nftUserOpsUserCollectionContractDetailsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for nftUserOpsUserCollectionContractDetailsPost call and complete the assertions
          /*

          instance.nftUserOpsUserCollectionContractDetailsPost(contractAddress, chain, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(VerbwireApiDocumentation.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
